name: travel
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.0.6 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter_svg: ^2.0.7
  flutter_screenutil: ^5.8.4
  get_storage: ^2.1.1
  geolocator: ^10.1.0
  google_fonts: ^6.1.0
  http: ^1.1.0 
  intl: ^0.18.1
  line_icons: ^2.0.3
  salomon_bottom_bar: ^3.3.2
  flutter_map: ^6.0.1
  latlong2: ^0.9.0
  flutter: 
    sdk: flutter
  geocoding: ^2.1.1
  lottie: ^2.7.0
  shimmer: ^3.0.0
  flutter_map_marker_popup: ^6.1.2
  dropdown_button2: ^2.3.9
  get_cli: ^1.8.1
  carousel_slider: ^4.2.1
  map_launcher: ^3.1.0

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
        - assets/

